# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83fd1297ef8f5967aa52b0c8051cfa1d5738e6980b5ac3b092df53019026d068c65049577b5940bb0a61066032d2866db2282f5415da0c41f59c68c5939767a1

test:
  secret_key_base: ab54d28b01c3fde1768076ce6ab4d28d2647ea4f2653dfc8c7817994098839a3f1e061d9797fbc3d1a29039241be009f1293a784576611574a1e48deaba745ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
